spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        port: 8085
        git:
          uri: https://github.com/kpate402/microserviceconfig.git
          clone-on-start: true

  profiles:
    default: true